### ISSUE TITLE
Game does not launch!

### ISSUE THREAD

**Issue by KurewskiPies** [Aelto/tw3-consumables-on-cooldowns#1]
Hey, i installed the mod, following the instructions exactly, yet i get a script compilation error:
Error [modconsumablesoncooldowns]local\consumables-on-cooldowns\main.ws(16): 'custom_cooldowns' is not a member of 'handle:CR4Player'
Error [modconsumablesoncooldowns]local\consumables-on-cooldowns\main.ws(18): 'custom_cooldowns' is not a member of 'handle:CR4Player'

Warning [content0]engine\environment.ws(30): Global native function 'EnableDebugOverlayFilter' was not exported from C++ code.
Warning [content0]engine\environment.ws(32): Global native function 'EnableDebugPostProcess' was not exported from C++ code.
Warning [content0]engine\showflags.ws(11): Global native function 'DebugSetEShowFlag' was not exported from C++ code.

I don't know what caused it, but it does not seem like a merging issue or a conflict with other mods. Script Merger merged everything automatically without any issues. So maybe there's some issue in the mod itself? Or maybe i have, in fact a compatibility issue here.

**Comment by Aelto** [comment]
Hi,

You are right, it seems i made a little mistake when publishing the release. I will fix it right now a push a new one. Thanks for the report!

**Comment by Aelto** [comment]
Alright, this is fixed. You can find the correct release here: [v1.1](https://github.com/Aelto/tw3-consumables-on-cooldowns/releases/tag/v1.1).

Thank you again for the issue, i wouldn't have noticed myself as it was a release issue and the version i currently have on my game was the correct one!
